daisyproject/address/urls.py
from.import views
from django.urls import path

app_name = 'address'
urlpatterns = [
    path('', views.AddressListView.as_view(), name='address_changelist'),
    path('add/', views.AddressCreateView.as_view(), name='address_add'),
    path('<int:pk>/', views.AddressUpdateView.as_view(), name='address_change'),
    path('ajax/load-sellers/', views.load_sellers, name='ajax_load_sellers'),

]

daisyproject/cart/urls.py
from django.urls import path
from.import views

app_name = 'cart'
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
    ]

daisyproject/connect/urls.py
from . import views
from django.urls import path
app_name = 'connect'
urlpatterns = [
    path('cat/', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatdetail'),
    ]

daisyproject/daisyproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flower.urls')),
    path('connect/', include('connect.urls')),
    path('cart/', include('cart.urls')),
    path('address/', include('address.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

daisyproject/flower/urls.py
from . import views
from django.urls import path
app_name = 'flower'
urlpatterns = [
    path('', views.home, name='home'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

daisyproject/cart/models.py
from django.db import models
from connect.models import Product
# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

daisyproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from connect.models import Product
from.models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

daisyproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>complete responsive flower website design tutorial</title>
    <link rel="icon" type="image" href="{% static 'images/flo.png' %}">
    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/cust.css' %}">
    <link rel="stylesheet" href="{% static 'css/customm.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


</head>
<body>
<div class="">
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}
</div>

</body>

<!--<script src="{% static 'js/slim.min.js' %}" ></script>-->
<!--<script src="{% static 'js/popper.min.js' %}"></script>-->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<!--<script src="{% static 'js/jquery.min.js' %}"></script>-->
<!--<script src="{% static 'js/script.js' %}"></script>-->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"></script>
</html>

daisyproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<br><br><br><br><br><br>
{% if not cart_items %}
<div> <br><br><br><br><br><br>
    <div class="text-center">
        <br>
        <h1 class="text-center my-title">
            Your Shopping Cart is empty
        </h1>

        <a class="nav-link" href="{% url 'connect:allProdCat' %}"> <img src="{% static 'images/cartpic.png' %}" alt="" width="70" height="70" class="d-inline-block align-top"></a>
        <br>
        <p class="text-center">
            Please Click <a href="{% url 'connect:allProdCat' %}">Here</a> to continue shopping.
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    Your Items

                </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="{{ cart_item.product.get_url }}"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image"></a>
                </td>
                <td class="text-left col-lg-4">
                    <b>{{cart_item.product.name}}</b>
                    <br>
                    SKU: {{cart_item.product.id}}
                    <br>
                    Price:  <i class="fas fa-rupee-sign"></i> {{cart_item.product.price}}
                    <br>
                    Bunch: {{cart_item.quantity}} x <i class="fas fa-rupee-sign"></i> {{cart_item.product.price}}
                </td>
                <td>
                   <i class="fas fa-rupee-sign"></i><strong> {{cart_item.sub_total}}</strong>
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fas fa-plus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash custom_icon"></i></a>
                </td>
                {% else %}
                <td>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
        <thead class="my_custom_thead">
        <tr>
            <th>
                Checkout
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                Please review your shopping cart items before proceeding with the order payment.
            </td>
        </tr>
        <tr>
            <td class="text-center">
                 Your Total is : <i class="fas fa-rupee-sign"></i> <strong>{{ total }}</strong>
            </td>
        </tr>
        </tbody>
    </table>

        {% if not address_add %}
        <div class="mx-auto col-lg-4 col-md-12 btttnn"  >
        <a href="{% url 'address:address_changelist' %}" style="color:white;" >Pay Now</a>
            {% else %}
             <div class="mx-auto col-lg-4 col-md-12 btttnn"  >
        <a href="{% url 'connect:allProdCat' %}" style="color:white;" >Pay Now</a>
                 {% endif %}

    </div><br>
       <p style="font-size:20;"> Do you want to continue?</p><br>
    <div class="mx-auto col-lg-4" style="background-color:#FFC300; width=30; height=20;" >
        <a href="{% url 'connect:allProdCat' %}" style="color:white;"><b>Continue Shopping</b></a>
    </div>


  </div>
    </div>

</div>
    </div>


{% endif %}
{% endblock %}

daisyproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if category %}
<div xmlns="http://www.w3.org/1999/html">
        <div class="row my_row_class">
            <div class="mx-auto">
           <p><a href="{% url 'connect:allProdCat' %}">Our product collections</a></p>
        </div>
            </div>
     </div>
  {% endif %}
  <div class="mx-auto">
     {% if category %}
       <h1 class="text-center my_title" style="font-size:25px;"><b>{{category.name}}</b></h1>
  </div>
     {% else %}
     <div class="home_page" >
   <div class="content">
        <h1 style="color:white; text-align:center;">Fresh Flowers</h1>
       <p style="color:white; text-align:center;">A flower, sometimes known as a bloom or blossom, is the reproductive structure found in flowering plants (plants of the division Angiospermae). The biological function of a flower is to facilitate reproduction, usually by providing a mechanism for the union of sperm with eggs. Flowers may facilitate outcrossing (fusion of sperm and eggs from different individuals in a population) resulting from cross-pollination or allow selfing (fusion of sperm and egg from the same flower) when self-pollination occurs.</p>
       </div>
         </div>
{% endif %}
<div class="flower">
    <div class="row mx_auto">
      {% for product in products.object_list %}
       <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
        <div class="class text-center">
          <a href="#"><img class="card-img-top my_image"  src="{{product.image.url}}" alt="{{product.name}}"></a>
            <div class="card-body">
             <h4>{{product.name}}</h4>
             <p><i class="fas fa-rupee-sign"></i> <strong>{{product.price}}</strong></p>
                  {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>Out of stock</b></p>
            {% else %}
            <a class="btn btn-success" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
            {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    </div>
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}
        <br>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
        {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>

      <section class="products" id="gallery">

    <h1 class="heading"> <span>Gallery</span> </h1>
      </section>

        <div class="gallery">
    <img src="{% static 'images/bg5.jpg' %}" alt="Cinque Terre" width="600" height="400">
  <div class="desc">Daisy</div>
</div>

<div class="gallery">
    <img src="{% static 'images/bg6.jpg' %}" alt="Forest" width="600" height="400">
  <div class="desc">Daffodils</div>
</div>
        <div class="gallery">
    <img src="{% static 'images/bg7.jpg' %}" alt="Forest" width="600" height="400">
  <div class="desc">Dahlia</div>
</div>
        <div class="gallery">
    <img src="{% static 'images/chry.jpg' %}" alt="Forest" width="600" height="400">
  <div class="desc">chrysanthemum</div>
</div>
         <div class="gallery">
    <img src="{% static 'images/bg9.jpg' %}" alt="Forest" width="600" height="400">
  <div class="desc">Lily</div>
</div>
        <div class="gallery">
    <img src="{% static 'images/bg10.jpg' %}" alt="Forest" width="600" height="400">
  <div class="desc">Hollyhock</div>
</div>
        <div class="gallery">
    <img src="{% static 'images/bg11.jpg' %}" alt="Forest" width="600" height="400">
  <div class="desc">Lilac</div>
</div>
        <div class="gallery">
    <img src="{% static 'images/bg12.jpg' %}" alt="Forest" width="600" height="400">
  <div class="desc">Primrose</div>
</div>

 <div class="gallery">
    <img src="{% static 'images/bg12.jpg' %}" alt="Forest" width="600" height="400">
  <div class="desc">Primrose</div>
</div>

 <div class="gallery">
    <img src="{% static 'images/bg12.jpg' %}" alt="Forest" width="600" height="400">
  <div class="desc">Primrose</div>
</div>

 <div class="gallery">
    <img src="{% static 'images/tulip.jpg' %}" alt="Forest" width="600" height="400">
  <div class="desc">Tulip</div>
</div>

 <div class="gallery">
    <img src="{% static 'images/picc1.jpg' %}" alt="Forest" width="600" height="400">
  <div class="desc">Aubrieta</div>
</div>
<br><br><br>



{% endblock %}

daisyproject/templates/footer.html
<!--<footer class="sticky-footer">-->
<div class="foot fixed-bottom my_footer">
    <p class="text-center">&copy; Flower. | All Rights Reserved.</p>
</div>
<!--</footer>-->

daisyproject/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>complete responsive flower website design tutorial</title>
    <link rel="icon" type="image" href="{% static 'images/flo.png' %}">
    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/stylecus.css' %}">

</head>
<body>

<!-- header section starts  -->

<header>

    <input type="checkbox" name="" id="toggler">
    <label for="toggler" class="fas fa-bars"></label>

    <a href="{% url 'flower:home' %}" class="logo"><img src="{% static 'images/flo.png' %}" width="40" height="40"> flower<span>.</span></a>

    <nav class="navbar">
        <ul class="d-flex flex-row align-items-start justify-content-start">
        <a href="#home">home</a>
        <a href="#about">about</a>
        <a href="#products">products</a>
        <a href="#review">review</a>
        <a href="#contact">contact</a>
<!--        <div class="nav-item dropdown {% if 'flower' in request.path %} active {% endif %}">-->
<!--        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">-->
<!--          Places</a>-->
<!--            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--                <li><a href="https://en.wikipedia.org/wiki/Palakkad">Palakkad</a></li>-->
<!--                <li><a href="https://en.wikipedia.org/wiki/Idukki_district">Idukki</a></li>-->
<!--                <li><a href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a></li>-->
<!--                <li><a href="https://en.wikipedia.org/wiki/Kottayam">Kottayam</a></li>-->
<!--                <li><a href="https://en.wikipedia.org/wiki/Malappuram">Malappuram</a></li>-->
<!--                <li><a href="https://en.wikipedia.org/wiki/Wayanad_district">Wayanad</a></li>-->
<!--                <li><a href="https://en.wikipedia.org/wiki/Kannur">Kannur</a></li>-->

<!--            </ul>-->
<!--            </div>-->
             </ul>
        &nbsp;
       <div>
        <ul>
        {% if user.is_authenticated %}
            <div><a><b>Hello {{user.username}}</b></a>
            <a href="flower/logout">Logout</a></div>
            {% else %}
            <div><a href="flower/register"></a>
            <a href="flower/login"></a></div>
            {% endif %}
            </ul>
            </div>
         </nav>


    <div class="icons">
        <a href="{% url 'connect:allProdCat' %}" class="fas fa-heart"></a>
        <a href="{% url 'cart:cart_detail' %}" class="fas fa-shopping-cart"></a>
<!--        <a href="#" class="fas fa-user"></a>-->
    </div>

</header>

<!-- header section ends -->

<!-- home section starts  -->

<section class="home_page" id="home">
<div class="center">
      <h1>Login</h1>
      <form action="login" method="post">
          {% csrf_token %}
        <div class="txt_field">
          <input type="text" name="username" required>
          <span></span>
          <label>Username</label>
        </div>
        <div class="txt_field">
          <input type="password" name="password" required>
          <span></span>
          <label>Password</label>
        </div>
        <div class="pass">Forgot Password?</div>
        <input type="submit" value="Login">
        <div class="signup_link">
          Not a member? <a href="{% url 'flower:register' %}">Register</a>
        </div>
      </form>
          {% for msg in messages %}
				<h2>{{msg}}</h2>
				{% endfor %}

</div>

</section>

daisyproject/templates/nav.html
{% load static %}
<header>
    <input type="checkbox" name="" id="toggler">
    <label for="toggler" class="fas fa-bars"></label>

    <a href="{% url 'flower:home' %}" class="logo"><img src="{% static 'images/flo.png' %}" width="40" height="40"> flower<span>.</span></a>

    <nav class="navbar">
        <ul class="d-flex flex-row align-items-start justify-content-start">
        <a href="{% url 'flower:home' %}">home</a>

             <li class="nav-item dropdown {% if 'connect' in request.path %} active {% endif %}">
        <a class="anav-link dropdown-toggle"  href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
          Categories
        </a>
        <ul class="dropdown-menu"  aria-labelledby="navbarDropdown">
            {% for cat in links %}
          <li><a class="dropdown-item"  href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
        </ul>
      </li>
            <a href="#gallery">Gallery</a>

             </ul>
        &nbsp;
       <div>
        <ul>
        {% if user.is_authenticated %}
            <div><a><b>Hello {{user.username}}</b></a>
            <a href="{% url 'flower:logout' %}">Logout</a></div>
            {% else %}
            <div><a href="{% url 'flower:register' %}"></a>
            <a href="{% url 'flower:login' %}"></a></div>
            {% endif %}
            </ul>
            </div>
         </nav>


    <div class="icons">
        <a href="{% url 'connect:allProdCat' %}" class="fas fa-heart"></a>
        <a href="{% url 'cart:cart_detail' %}" class="fas fa-shopping-cart"></a>

    </div>

</header>

daisyproject/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>complete responsive flower website design tutorial</title>
    <link rel="icon" type="image" href="{% static 'images/flo.png' %}">
    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/stylecus.css' %}">

</head>
<body>

<!-- header section starts  -->

<header>

    <input type="checkbox" name="" id="toggler">
    <label for="toggler" class="fas fa-bars"></label>

    <a href="{% url 'flower:home' %}" class="logo"><img src="{% static 'images/flo.png' %}" width="40" height="40"> flower<span>.</span></a>

    <nav class="navbar">
        <ul class="d-flex flex-row align-items-start justify-content-start">
        <a href="{% url 'flower:home' %}">home</a>
        <a href="#about">about</a>
        <a href="#products">products</a>
        <a href="#review">review</a>
        <a href="{% url 'flower:login' %}">Login</a>
             </ul>

       <div>
        <ul>
        {% if user.is_authenticated %}
            <div><a><b>Hello {{user.username}}</b></a>
            <a href="{% url 'flower:logout' %}">Logout</a></div>
            {% else %}
            <div><a href="{% url 'flower:register' %}"></a>
            <a href="{% url 'flower:login' %}"></a></div>
            {% endif %}
            </ul>
            </div>
         </nav>


    <div class="icons">
        <a href="{% url 'connect:allProdCat' %}" class="fas fa-heart"></a>
        <a href="{% url 'cart:cart_detail' %}" class="fas fa-shopping-cart"></a>

    </div>

</header>

<!-- header section ends -->

<!-- home section starts  -->

<section class="home_page" id="home">

<div class="center">
      <h1>Register</h1>
      <form action="register" method="post">
          {% csrf_token %}
        <div class="txt_field">
          <input type="text" name="username" required>
          <span></span>
          <label>Username</label>
        </div>

          <div class="txt_field">
          <input type="text" name="email" required>
          <span></span>
          <label>Email</label>
        </div>


        <div class="txt_field">
          <input type="password" name="password" required>
          <span></span>
          <label>Password</label>
        </div>

          <div class="txt_field">
          <input type="password" name="password1" required>
          <span></span>
          <label>Confirm Password</label>
        </div>

        <input type="submit" value="Register">
        <div class="signup_link">
          Already have account? <a href="{% url 'flower:login' %}">Login</a>
        </div>
      </form>
          {% for msg in messages %}
				<h2>{{msg}}</h2>
				{% endfor %}

</div>

</section>