daisyproject/address/urls.py
from.import views
from django.urls import path

app_name = 'address'
urlpatterns = [
    path('', views.AddressListView.as_view(), name='address_changelist'),
    path('add/', views.AddressCreateView.as_view(), name='address_add'),
    path('<int:pk>/', views.AddressUpdateView.as_view(), name='address_change'),
    path('ajax/load-sellers/', views.load_sellers, name='ajax_load_sellers'),

]

daisyproject/cart/urls.py
from django.urls import path
from.import views

app_name = 'cart'
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
    ]

daisyproject/daisyproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flower.urls')),
    path('connect/', include('connect.urls')),
    path('cart/', include('cart.urls')),
    path('address/', include('address.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

daisyproject/address/models.py
from django.db import models

# Create your models here.
class District(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name



class Seller(models.Model):
    name = models.CharField(max_length=250)
    district = models.ForeignKey(District, on_delete=models.CASCADE)

    def __str__(self):
        return self.name



class Customer(models.Model):
    name = models.CharField(max_length=100)
    mobileno = models.IntegerField()
    address = models.CharField(max_length=250)
    pincode = models.IntegerField()
    district = models.ForeignKey(District, on_delete=models.SET_NULL, null=True)
    seller = models.ForeignKey(Seller, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

daisyproject/address/forms.py
from django import forms

from .models import Seller, Customer


class AddAddressForm(forms.ModelForm):
    error_css_class = 'error-field'
    required_css_class = 'required-filed'
    name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    mobileno = forms.IntegerField(widget=forms.TextInput(attrs={"class": "form-control"}))
    address = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    pincode = forms.IntegerField(widget=forms.TextInput(attrs={"class": "form-control"}))
    class Meta:
        model = Customer
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['seller'].queryset = Seller.objects.none()

        if 'district' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['seller'].queryset = Seller.objects.filter(district_id=district_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['seller'].queryset = self.instance.district.seller_set.all()

daisyproject/address/views.py
# from django.shortcuts import render, redirect, get_object_or_404
# from . models import District, Seller, Customer
# from .forms import AddAddressForm
# # Create your views here.
# def address_list_view(request):
#     form = AddAddressForm
#     return render(request, 'delivery.html', {'form': form})
#
# def address_create_view(request):
#     form = AddAddressForm()
#     if request.method == 'POST':
#         form = AddAddressForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('address_add')
#     return render(request, 'address.html', {'form': form})
#
#
# def address_update_view(request, pk):
#     customer = get_object_or_404(Customer, pk=pk)
#     form = AddAddressForm(instance=customer)
#     if request.method == 'POST':
#         form = AddAddressForm(request.POST, instance=customer)
#         if form.is_valid():
#             form.save()
#             return redirect('address_change', pk=pk)
#     return render(request, 'address.html', {'form': form})
#
# # AJAX
# def load_sellers(request):
#     district_id = request.GET.get('district_id')
#     sellers = Seller.objects.filter(district_id=district_id).all()
#     return render(request, 'add.html', {'sellers': sellers})
#
#-----------------------------------------------------------------------------------------------------------

from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy

from . forms import AddAddressForm
from .models import Customer, Seller


class AddressListView(ListView):
    model = Customer
    context_object_name = 'address'


class AddressCreateView(CreateView):
    model = Customer
    form_class = AddAddressForm
    success_url = reverse_lazy('address_changelist')


class AddressUpdateView(UpdateView):
    model = Customer
    form_class = AddAddressForm
    success_url = reverse_lazy('address_changelist')


def load_sellers(request):
    district_id = request.GET.get('district_id')
    sellers = Seller.objects.filter(district_id=district_id).all()
    return render(request, 'address/add.html', {'sellers': sellers})

daisyproject/address/templates/address/add.html
<option value="">---------</option>
{% for seller in sellers %}
<option value="{{ seller.pk }}">{{ seller.name }}</option>
{% endfor %}

daisyproject/address/templates/address/customer_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<br><br><br><br><br><br>
 <section class="products">

    <h1 class="heading"> <span>Add Address</span> </h1>
      </section>
<form method="post" id="customerForm" data-sellers-url="{% url 'address:ajax_load_sellers' %}" >
          {% csrf_token %}
     <div class="justify-content-center">
                                        <div class="card card-custom pb-4 col-12">
                                            <div class="card-body mt-0">
                                                <div class="text-center mb-3 pb-2 mt-3">
                                                    <h4 style="color: #495057 ;"><b>Delivery Address</b></h4>
                                                </div>
<div class="row mb-4">
                                                    <div class="col">
                                                        <div class="form-outline">
                                                            <label class="form-label" for="form9Example1"><b>Name:</b></label>
                                                            <!-- <input type="text" value="{{ form.name }}" name="name" class="form-control input-custom" /> -->
                                                            {{form.name}}
                                                        </div>
                                                    </div>
                                                    <div class="col">
                                                        <div class="form-outline">
                                                            <label class="form-label" for="form9Example2"><b>Phone
                                                                Number:</b></label>
                                                            {{ form.mobileno }}
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row mb-4">
                                                    <div class="col">
                                                        <div class="form-outline">
                                                            <label class="form-label"
                                                                for="form9Example3"><b>Address:</b></label>
                                                            {{ form.address }}
                                                        </div>
                                                    </div>
                                                    <div class="col">
                                                        <div class="form-outline">
                                                            <label class="form-label" for="form9Example4"><b>Pincode:</b></label>
                                                            {{ form.pincode }}
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row mb-4">
                                                    <div class="col">
                                                        <div class="form-outline">
                                                            <label class="form-label"
                                                                for="form9Example6"><b>District:</b></label>{{ form.district }}
                                                        </div>
                                                    </div>
                                                    <div class="col">
                                                        <div class="form-outline">
                                                            <label class="form-label" for="typeEmail"><b>Seller:</b></label>
                                                            {{ form.seller }}
                                                        </div>
                                                    </div>
                                                </div>


          <button type="submit">Save</button>
               <a href="{% url 'address:address_changelist' %}">Nevermind</a>

        </div>
                                            </div>
                                        </div>

      </form>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
           <script>
    $("#id_district").change(function () {
        const url = $("#customerForm").attr("data-sellers-url");
        const districtId = $(this).val();

        $.ajax({
                url: url,
                data: {
                    'district_id': districtId
            },
            success: function (data) {
                     console.log(data)
                    $("#id_seller").html(data);

<!--                     let html_data = '<option value="">-&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</option>';-->
<!--                    data.forEach(function (seller) {-->
<!--                        html_data += `<option value="${seller.id}">${seller.name}</option>`-->
<!--                    });-->
<!--                    console.log(html_data);-->
<!--                    $("#id_seller").html(html_data);-->



            }
        });

    });
</script>


{% endblock %}

daisyproject/address/templates/address/customer_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br><br><br><br><br><br>
<section class="products">

    <h1 class="heading"> <span>Delivery Address</span> </h1>
      </section>
     <p>
    <a href="{% url 'address:address_add' %}">Add Address</a>
  </p>

   <table border="1">
    <thead>
      <tr>
        <th>Name</th>

        <th>district</th>
        <th>seller</th>
      </tr>
    </thead>
    <tbody>
      {% for cus in address %}
        <tr>
          <td><a href="{% url 'address_change' address.pk %}">{{ cus.name }}</a></td>

          <td>{{ cus.district.name }}</td>
          <td>{{ cus.seller.name }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">No address. <a href="{% url 'address:address_add' %}">Add the first address</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>



{% endblock %}